### ISSUE TITLE
希望复制链接的窗口，改为将所有自定义域名的相关链接直接展示出来，在每个链接后面有个复制功能

### ISSUE THREAD

**Issue by moobing** [qiniu/kodo-browser#113]
现在是要下拉选择自定义域名后，点生成，才可以获取完整链接，操作过于繁琐了

**Comment by Jessie-shsh** [comment]
暂时不考虑支持。需要同时复制多个外链的情况较少，对于域名多、但不需要复制多个外链的用户干扰较大

**Comment by moobing** [comment]
目前是连复制一个外链都很繁琐，就希望减少操作步骤而已，问题的关键不在复制多个外链而是操作繁琐
