### ISSUE TITLE
Buket根目录下有很多文件和少量目录打开时卡很久

### ISSUE THREAD

**Issue by tangwan** [qiniu/kodo-browser#116]
MacOS KODO 浏览器 v1.0.17

1. 进入bucket能否把目录拍前面?
2. 控制加载文件和目录数量,不然太卡了,软件都卡死了只能杀进程.

**Comment by bachue** [comment]
1. 服务器端限制，不可以
2. 开启分布加载即可

<img width="1002" alt="Screen Shot 2022-05-20 at 3 32 12 PM" src="https://user-images.githubusercontent.com/321962/169477036-af436f41-a196-4db8-9b6b-53d954613220.png">
