### ISSUE TITLE
大大们麻烦加一下清除cdn缓存的功能

### ISSUE THREAD

**Issue by iamxz** [qiniu/kodo-browser#12]

**Comment by cycychenyi** [comment]
期待 CDN 缓存功能 +1

**Comment by Jessie-shsh** [comment]
再更详细的描述一下具体需求或操作场景？

**Comment by cycychenyi** [comment]
比如上传了一张图片到 http://mysite.com/path/to/image.png，然后发现图片错了，删除错误的图片，将正确的图片重新上传到相同的地址。如果没有清除 CDN 缓存，返回的还是错误的图片，需要刷新一下。

**Comment by Jessie-shsh** [comment]
@iamxz @cycychenyi  CDN 缓存自动刷新功能，默认不开启，因为七牛CDN的刷新额度是有一定限制的。确实有需求的话，可以提交工单给我们的技术支持同学处理。

**Comment by bachue** [comment]
无法支持
