### ISSUE TITLE
文件多了就巨卡

### ISSUE THREAD

**Issue by ShenKang4181** [qiniu/kodo-browser#122]
文件多了就巨卡！
希望能优化一下

**Comment by bachue** [comment]
是哪里比较卡？列举吗？

**Comment by ShenKang4181** [comment]
> 

加载文件列表就巨卡，超过5000之后几乎卡的动不了
![image](https://user-images.githubusercontent.com/50401776/177131151-42b354bc-8828-4921-810c-130fe2fb5817.png)

**Comment by ShenKang4181** [comment]
> 是哪里比较卡？列举吗？

请问有好用的七牛客户端吗？
或者第三方的？
找了好久了都没有好使的

**Comment by ShenKang4181** [comment]
这    /[捂脸笑]
不卡的秘诀竟然是 “不要加载那么多数据”
![QQ图片20220705092101](https://user-images.githubusercontent.com/50401776/177231459-abca2b6c-1999-4bef-b67d-4a2b048b4556.jpg)

**Comment by bachue** [comment]
目前确实只有这种处理方案，两个版本后会规划这部分优化的。

**Comment by ShenKang4181** [comment]
> 目前确实只有这种处理方案，两个版本后会规划这部分优化的。

好吧，期待哦
