### ISSUE TITLE
希望能增加“同时下载数量选项”

### ISSUE THREAD

**Issue by ShenKang4181** [qiniu/kodo-browser#123]
希望能增加“同时下载数量选项”
现在是一个下载完了再下一个，如果我要下载2000个文件，要下一上午
而且切到后台等会儿就自己暂停了
还得盯着他
时不时得清理一下下载完的任务
不然有可能卡住不下了
希望能优化一下

**Comment by bachue** [comment]
<img width="599" alt="Screen Shot 2022-07-05 at 9 07 44 AM" src="https://user-images.githubusercontent.com/321962/177230578-fc847df2-af21-4930-bd3a-d66a72081b55.png">
这个选项就是用来设置最大并发下载数量的，设到 10 就行了。

**Comment by ShenKang4181** [comment]
啊这 原来在这里
试了一下，快的飞起
![QQ图片20220705091707](https://user-images.githubusercontent.com/50401776/177231209-dd1c10e8-3e4c-45fc-b328-8cf4f4f4f70a.jpg)
