### ISSUE TITLE
希望能支持外链独立域名。

### ISSUE THREAD

**Issue by yoyomule** [qiniu/kodo-browser#13]
七牛的外链有独立域名，希望能够生成的地址是包含独立域名的。

**Comment by bachue** [comment]
@yoyomule 之后的版本将会支持的。

**Comment by Jessie-shsh** [comment]
内部跟踪issue编号 KODO-10300

**Comment by Jessie-shsh** [comment]
1.0.11版本，可以支持使用cdn域名生成外链，公开空间可以生成永久连接。
