### ISSUE TITLE
1.0.19版本文件夹归档不正确

### ISSUE THREAD

**Issue by HelloWorld-create** [qiniu/kodo-browser#130]
使用1.0.19版本windows64位客户端下载文件，文件夹内的内容无法被正确放置到文件夹内而是在文件夹外部，文件夹无法正确被递归。
1.0.18版本无此问题。

**Comment by bachue** [comment]
确定是 bug，将会紧急修复

**Comment by lihsai0** [comment]
@HelloWorld-create 已修复，请升级新版

**Comment by peteyan** [comment]
升级到1.0.19.1后，此问题仍旧存在。
![image](https://user-images.githubusercontent.com/9857264/186121241-9ed9ff65-c011-4e0c-bdea-84bc24b06170.png)
