### ISSUE TITLE
待上传文件拖放至kodo后，文件夹路径未生效，文件被改名并存放至根目录处

### ISSUE THREAD

**Issue by peteyan** [qiniu/kodo-browser#132]
#130 升级到1.0.19.1后，此问题仍旧存在。
![image](https://user-images.githubusercontent.com/9857264/186122990-409403e4-e956-4ab9-a1a7-686581e6c018.png)
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/9857264/186123495-989541f1-f779-416d-8b5b-db8030552a27.png">
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/9857264/186123959-b7e80517-1812-45c8-8020-113b5a73eaad.png">

**Comment by lihsai0** [comment]
https://user-images.githubusercontent.com/17806506/186137718-95b2bed1-9fb4-47c9-a854-eedca642f85a.mp4

未能复现，麻烦能否描述下操作步骤或录个视频？
