### ISSUE TITLE
程序无法运行 GPU process crashes with exit code -1073741819

### ISSUE THREAD

**Issue by Lrunlin** [qiniu/kodo-browser#135]

**Comment by bachue** [comment]
@Lrunlin  请提供具体的错误信息

**Comment by Lrunlin** [comment]
最新版本，/kodo-browser-win32-x86-v1.0.19.2.zip。
win11，
打开后白屏几秒然后自动关闭

**Comment by Lrunlin** [comment]
x64和x86都一样的错误

**Comment by lihsai0** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/17806506/192103955-953c589a-59b4-417e-a9eb-48a15069fcea.png">

@Lrunlin 您好，无法复现您说的情况。可以正常使用。

只有 Windows 有过打不开的情况是因为环境变量问题。建议您这边检查一下：

检查环境变量中是否有 NODE_OPTIONS 选项，其值为 --max-http-header-size=xxx。若有，删掉即可。注意用户变量与系统变量都要检查。据说是某次 windows 更新引起的。

设置环境变量：右键 Windows 徽标 → 系统 → 高级设置 → 环境变量

---

如果还是不行，需要您提供更多信息才能进一步排查。

**Comment by Lrunlin** [comment]
https://user-images.githubusercontent.com/54397964/192128149-df46f9aa-23d8-4e54-aff2-7350c11b4378.mp4

还是不行

**Comment by lihsai0** [comment]
@Lrunlin 您尝试从终端（Power Shell 之类的）启动一下程序，看看有没有什么错误信息。

**Comment by Lrunlin** [comment]
![image](https://user-images.githubusercontent.com/54397964/192130966-d183b99e-6074-4a4c-90c7-409dd86fe313.png)

**Comment by lihsai0** [comment]
@Lrunlin 这个似乎是上游的问题。建议更新显卡驱动等相关操作试试。

P.S. 有很多[关于这个问题的报告](https://github.com/electron/electron/issues?q=1073741819)。也可以翻阅一下，看看有没有人解决。

**Comment by Lrunlin** [comment]
好的，谢谢

**Comment by bachue** [comment]
@Lrunlin 请问这个问题现在解决了吗？

**Comment by Lrunlin** [comment]
> @Lrunlin 请问这个问题现在解决了吗？

没，下载就版本也不好使，electron issues又说升级electron版本的，别的方法没看到。也有说原因是部分显卡不兼容。

**Comment by lihsai0** [comment]
@Lrunlin 您这边  VS Code 能正常运行嘛？

我看 VS Code 也有类似的问题，不过 exit code 和咱们这个案例不一样。

尝试下在终端启动时添加 `--no-sandbox` 或 `--disable-gpu-sandbox` 等参数试试。
（参考 [VS Code 里相关的 issue](https://github.com/microsoft/vscode/issues?q=GPU+process+exited+unexpectedly)）

然后就是您可以尝试修改下文件 `src/main/index.ts` 添加上 [`app.disableHardwareAcceleration()`](https://github.com/electron/electron/blob/main/docs/api/app.md#appdisablehardwareacceleration) 自行编译一下试试。

最后看您这边好像是一个核显？可以检查看看核显驱动有没有更新什么。

**Comment by Lrunlin** [comment]
![image](https://user-images.githubusercontent.com/54397964/192793667-a7245a7f-f79f-4b80-b26d-ceaed9c84c95.png)

好使了
