### ISSUE TITLE
打开 Bucket ， 根目录有很多文件时，优化性能

### ISSUE THREAD

**Issue by limoning** [qiniu/kodo-browser#14]
mac电脑（或许windows也会） 
当打开的 Bucket 内 根目录有很多文件的时候，电脑cpu占用飙升
同样下载文件太多也会如此
希望能尽快优化

**Comment by bachue** [comment]
@limoning 目前加载一个庞大的目录时确实会有性能不佳的问题，之后会实现分页加载的功能。

**Comment by Jessie-shsh** [comment]
内部跟踪issue编号 KODO-10217

**Comment by Jessie-shsh** [comment]
@limoning 你好，空间目录分步加载模式已经在1.0.10支持。
