### ISSUE TITLE
key为空字符串时无法进行任何操作

### ISSUE THREAD

**Issue by zhangzqs** [qiniu/kodo-browser#142]
如图key为长度为0的空白字符串时
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/34616640/210030963-b2fad3f0-c023-4a49-a79f-54b067c67335.png">
无法删除
<img width="606" alt="image" src="https://user-images.githubusercontent.com/34616640/210030977-06f7029c-f3d7-43ce-9d0c-192f9f82962c.png">
无法下载
<img width="602" alt="image" src="https://user-images.githubusercontent.com/34616640/210030995-e7e0bb22-c11a-42d9-a19d-96fd775cbe59.png">

**Comment by lihsai0** [comment]
@zhangzqs 
已于 [v2.0.0](https://github.com/qiniu/kodo-browser/releases/tag/v2.0.0) 修复
