### ISSUE TITLE
新版本干什么啊，开启覆盖，还给我停止上传了

### ISSUE THREAD

**Issue by seven-cm** [qiniu/kodo-browser#144]
新版本干什么啊，开启覆盖，还给我停止上传了？搞什么鬼？
![image](https://user-images.githubusercontent.com/9991576/219258651-f01ac580-6f06-476e-97cc-1352821abc41.png)
![image](https://user-images.githubusercontent.com/9991576/219258734-c3df3fe9-30ff-4951-bc7c-0e6e53e6d251.png)

**Comment by lihsai0** [comment]
@seven-cm  您好，未能复现。这些已停止的任务是否可能是您之前未完成的上传任务？

如果强制退出 Kodo Browser，运行中或等待中的任务会自动停止，待您下次打开应用就会出现这样的列表。

看您截图，新增上传任务似乎正在运行？有 138 个已完成了。

**Comment by seven-cm** [comment]
![image](https://user-images.githubusercontent.com/9991576/219338317-a4babb3d-0e4b-4f35-8e6b-13513d8218b7.png)
覆盖上传，提示文件已存在页不能覆盖的么？

**Comment by seven-cm** [comment]
搞不懂什么问题，我清空所有任务，重新上传又可以了😔

**Comment by lihsai0** [comment]
那些前面的任务可能是您之前的旧任务。这些旧任务当时可能没有选择覆盖上传。

提示已存在的任务可以点击覆盖重试按钮上传。
