### ISSUE TITLE
不支持框选或者shift多选么

### ISSUE THREAD

**Issue by Yuelioi** [qiniu/kodo-browser#154]
不支持框选和shift多选么

**Comment by lihsai0** [comment]
暂不支持，以后会添加。
感谢您的反馈建议。

**Comment by lihsai0** [comment]
[v2.2.0](https://github.com/qiniu/kodo-browser/releases/tag/v2.2.0) 已支持：

- Shift 多选
- 选择当前路径（包括未加载的项目）
  - 当前路径存在未加载项目，勾选全选按钮时可触发选择当前路径按钮
