### ISSUE TITLE
enhancement: increase max allowed validity period for download link

### ISSUE THREAD

**Issue by networkhermit** [qiniu/kodo-browser#163]
版本：v2.0.0

问题：升级到v2.0.0版本后，下载链接有效期限制在了一天，这对企业对外分享资源下载链接很不方便，建议将其限制延长到至少一周。

相关代码：

https://github.com/qiniu/kodo-browser/blob/169772b0eb21bbe68b23fc3fc97158369f73c4a6/src/renderer/modules/qiniu-client-hooks/use-load-domains.ts#L12

https://github.com/qiniu/kodo-browser/blob/169772b0eb21bbe68b23fc3fc97158369f73c4a6/src/renderer/components/forms/generate-link-form.tsx#L243

https://github.com/qiniu/kodo-browser/blob/169772b0eb21bbe68b23fc3fc97158369f73c4a6/src/renderer/modules/i18n/lang/en-us.ts#L283-L285

**Comment by bachue** [comment]
@networkhermit 建议使用自定义 CDN 域名做分享，可以拥有更长的有效期时间

**Comment by networkhermit** [comment]
> 建议使用自定义 CDN 域名做分享，可以拥有更长的有效期时间

使用的这个bucket不需要开暂时也不打算开CDN，强制CDN做更长有效期的分享在用户的角度是没意义的，S3接口没有这种限制，我认为这更多的是客户端附加的约束，更改本地electron源码已经绕过这个限制了。

**Comment by networkhermit** [comment]
@bachue 为什么不顾用户的反馈就关闭了呢？而且也没有合理的解释，对于七牛云这种做法未免有些让人失望了
