### ISSUE TITLE
这是我用过最难用的垃圾软件

### ISSUE THREAD

**Issue by lingyun820** [qiniu/kodo-browser#176]

**Comment by lihsai0** [comment]
老板，我明白软件有很多不足。但我也不会读心术，具体哪里不好还请您指点一二。

**Comment by lingyun820** [comment]
批量下载很多文件，刚开始很快，下载一会又变得很慢，每次都要重启下软件才又快起来

**Comment by lihsai0** [comment]
已知问题，正在测试的版本已修复，请您稍安勿躁等候新版本。

**Comment by lingyun820** [comment]
也不是很多，也就几万个文件，我发现有时候没有全部下载完。下载任务列表能确保都加载进去了再开始下载吗？下载任务列表的条数的显示感觉不大对

**Comment by lingyun820** [comment]
还有我明明全选了所有的文件和目录，最后下载结束，发现有的目录没有下载下来

**Comment by lihsai0** [comment]
我这边测试三四万时会感知到变慢，具体取决于硬件环境，主要是持久化导致的问题。可以分批下载缓解。

下载任务是边列举边创建，如果列举结束前关闭应用有可能会导致丢失下载任务。

**Comment by lingyun820** [comment]
我这边电脑是16G内存，千M网络，分批下载也不方便，分页本来就很卡。文件在下载时，是不是会变卡，影响下载任务的列举和创建？如果会，还不如先列举创建完再开始下载。

**Comment by lingyun820** [comment]
![360截图20240328140509357](https://github.com/qiniu/kodo-browser/assets/11835255/89a17885-70f5-44ad-89e3-143cde8a9929)
是32G内存i5cpu

**Comment by lihsai0** [comment]
当前大量任务变卡变慢的主要原因是任务的持久化形式是一个大 json，每次任务变化都要重写一次这个大 json，导致了这个问题。

列举完再开始下载也是个方式，不过对于大量文件的场景，整体耗时应该会比当前这种要多，因为列举也是个耗时操作。

> 分页本来就很卡

这个是指什么的分页？具体现象是什么？文件列表的话，已经做了优化，应该不会太卡了才是。可以请您描述一下具体信息吗？例如版本号、加载的文件数量等。

**Comment by lingyun820** [comment]
不能用其它的储存方式吗？为什么用json来保存那么大的数据呢？

**Comment by lingyun820** [comment]
最重要的是一个稳定可靠，即使下载再快，如果下载下来的文件不完整，我们还是要重新下载一遍，这样花费的时间更多。

**Comment by lingyun820** [comment]
分页是比以前流畅多了

**Comment by lihsai0** [comment]
json 这个设计问题我不是很清楚，接手时就是这样了。

正在测试的版本主要存储方式已经改成 jsonl + 简易的 LSM Tree。

应该测试差不多了，您再耐心等待一下。

不完整的问题，我这边记录一下。后续可能通过文件支持跳过已下载的等方式来优化。

**Comment by lingyun820** [comment]
好的，辛苦了

**Comment by lingyun820** [comment]
不知道你们用的是什么语言开发的，像本地数据库可以用SQLite等

**Comment by lihsai0** [comment]
也考虑过。

但由于这个项目之前引用其他生态的模块出过问题。所以当前禁止引入 SQLite 这些依赖。
