### ISSUE TITLE
这个根据名称或状态搜索是怎么搜索状态？比如说搜正在上传中的或完成的或等待的或出错的

### ISSUE THREAD

**Issue by ShenKang4181** [qiniu/kodo-browser#181]
这个根据名称或状态搜索是怎么搜索状态？比如说搜正在上传中的或完成的或等待的或出错的
![image](https://github.com/qiniu/kodo-browser/assets/50401776/1b051e09-5f71-4680-ab49-3dc5e0d4a8b1)

**Comment by lihsai0** [comment]
<img width="576" alt="image" src="https://github.com/qiniu/kodo-browser/assets/17806506/d7c93aa6-ec09-4f5a-8da6-ff486407d418">

@ShenKang4181  
当前这里在传输任务有问题时会统计有问题的任务个数。
点击图标会自动填入对应状态的英文来过滤。

下个版本（v2.2.0）根据状态过滤会改善为一个单选菜单。

**Comment by lihsai0** [comment]
[v2.2.0](https://github.com/qiniu/kodo-browser/releases/tag/v2.2.0) 已发布
