### ISSUE TITLE
1.能不能不显示9999+显示真实数字2.能不能根据名称时间大小等排序啊？

### ISSUE THREAD

**Issue by ShenKang4181** [qiniu/kodo-browser#183]
1.能不能不显示9999+显示真实数字2.能不能根据名称时间大小等排序啊？
![image](https://github.com/qiniu/kodo-browser/assets/50401776/db664f28-a121-4cb6-b45a-5a174ad1f309)

**Comment by ShenKang4181** [comment]
还有一个问题：（我猜测）因为没有真实数字只有9999+，再估计算上加载一次1000条时间的话，大概十几万条时就非常卡了，列表属于划不动的状态

**Comment by lihsai0** [comment]
1. `9999+` 主要是 UI 布局的问题。工具栏的空间着实不多。其次是因为这个路径下有多少内容是未知的，这里只能显示已加载的数目。后面可以考虑加一个悬浮提示框显示当前已加载的数目。
2. 排序服务端没有相关能力，单客户端做的意义不大。
3. 万级别的浏览应该不成问题，十万级别的目录浏览没有实际测试过，如果内存够大的话应该是可以的。
