### ISSUE TITLE
2.3.0版本导出外链选域名后默认没有显示https?

### ISSUE THREAD

**Issue by ExpGitHubUp** [qiniu/kodo-browser#187]
如题
2.3.0版本导出外链选域名后默认没有显示https

2.1.2版本没有这个问题 默认会显示https

推荐勾选自有域名后记住配置.下次启动后不用再次选择域名,默认域名协议http或https建议放在设置里面设定

**Comment by lihsai0** [comment]
@ExpGitHubUp

请问是什么类型的域名没有 https？这个域名绑定了证书了已经是吗？

**Comment by ExpGitHubUp** [comment]
> @ExpGitHubUp
> 
> 请问是什么类型（CDN/源站/是否 S3）的域名没有 https？这个域名绑定了证书了已经是吗？

是cdn
域名已经绑定了HTTPS

**Comment by lihsai0** [comment]
在 v2.3.1 已优化
