### ISSUE TITLE
v2.3.0 点下载报错 没有可用的域名获取对象

### ISSUE THREAD

**Issue by oohug** [qiniu/kodo-browser#188]

**Comment by oohug** [comment]
![image](https://github.com/qiniu/kodo-browser/assets/9601658/343ae286-fb20-4554-9267-e74cd29ec19b)

**Comment by lihsai0** [comment]
@oohug

v2.2.x 是否正常工作？

进入空间时有无错误信息？

公有云/私有云？私有云请向管理员确认是否禁用非自有域名

**Comment by lihsai0** [comment]
可能部分域名信息获取失败导致。已于 v2.3.1 优化。

若无改善，请重新打开这个问题。
