### ISSUE TITLE
功能建议：复制外链支持域名+路径

### ISSUE THREAD

**Issue by xmsz** [qiniu/kodo-browser#19]
理想中，应该是这个功能。而现在居然是复制一个临时外链地址..
![image](https://user-images.githubusercontent.com/5879146/84219899-15ab7b00-ab04-11ea-973a-7a2d65f5e9d9.png)

**Comment by RainingNight** [comment]
+1

**Comment by bachue** [comment]
@xmsz @RainingNight 暂时还不支持，之后的版本会改进的

**Comment by daqueque** [comment]
+1

**Comment by Jessie-shsh** [comment]
内部跟踪issue编号 KODO-10300

**Comment by Jessie-shsh** [comment]
1.0.11版本，可以支持使用cdn域名生成外链，公开空间可以生成永久连接

**Comment by RainingNight** [comment]
Nice
