### ISSUE TITLE
如果文件大于1.64G 则会下载失败

### ISSUE THREAD

**Issue by wangbodbs** [qiniu/kodo-browser#22]
如果文件大于1.64G 则会下载失败

**Comment by bachue** [comment]
@wangbodbs  目前的上传和下载的质量不高，之后的版本会逐步改进的

**Comment by Jessie-shsh** [comment]
内部跟踪issue编号 KODO-10301

**Comment by bachue** [comment]
@wangbodbs 请尝试下新的版本 v1.0.13，已经优化了下载质量
