### ISSUE TITLE
别人授权给我的私有空间无法显示在Kodo bucket列表中

### ISSUE THREAD

**Issue by Horse888** [qiniu/kodo-browser#23]
别人授权给我的私有空间无法显示在Kodo bucket列表中, 但是在浏览器端是可以看到的.

**Comment by bachue** [comment]
@ZuYuanZhou 暂时还未能支持，之后会开发该功能的。

**Comment by Jessie-shsh** [comment]
内部跟踪issue编号 KODO-10302

**Comment by ZuYuanZhou** [comment]
@bachue 这个功能应该是比较简单的, 是否能在下一个发布中更新呢? @Jessie-shsh

**Comment by moonsolar** [comment]
@bachue @Jessie-shsh 因为我想把空间授权给别人操作里面的内容, 这个功能什么时候可以发布呢?

**Comment by Jessie-shsh** [comment]
你好～预计在1.0.12版本发布这个功能

**Comment by bachue** [comment]
@Horse888 @moonsolar 这个功能已经于 v1.0.13 发布了
