### ISSUE TITLE
KODO browser 登陆时不能粘贴ak/sk

### ISSUE THREAD

**Issue by muriel01** [qiniu/kodo-browser#30]
1.0.10版本客户端登陆时无法在输入框粘贴ak/sk

**Comment by bachue** [comment]
@muriel01 你好～ 我们在各平台上都有确认，可以支持 ctrl+c 、 ctrl+v 的复制粘贴操作。客户端登录页面的输入框不支持右键操作，只支持快捷方式的 ctrl+v 粘贴。请注意下是否是浏览器限制或其他工具的使用，导致没有复制到 ak/sk 信息
