### ISSUE TITLE
全局监听快捷键打开devtools?

### ISSUE THREAD

**Issue by shankesgk2** [qiniu/kodo-browser#32]
v1.0.10
只要打开kodo,即使当前窗口不是kodo,按`option` + `command` + `i` kodo也会打开devtools.并且我当前窗口chrome没有打开devtools
全局监听快捷键了?好奇怪,可以修复一下吗?

**Comment by bachue** [comment]
@shankesgk2  我这边没有能重现，能否提供更多信息？

**Comment by shankesgk2** [comment]
不打开kodo是时候,当前窗口chrome,按 `option` + `command` + `i` 会打开devtools,打开kodo后,即使kodo不是当前窗口,按 `option` + `command` + `i` 也会打开kodo的devtools,而不是打开当前窗口的devtools,就是kodo抢占当前窗口chrome的按键了?
![iShot2020-09-26 14 39 00](https://user-images.githubusercontent.com/8123290/94332323-d5b2ca00-0006-11eb-8e98-f4d5fc8c51ce.gif)

**Comment by bachue** [comment]
@shankesgk2  好的 我这边尝试解决下

**Comment by Jessie-shsh** [comment]
1.0.11版本已修复此问题
