### ISSUE TITLE
【Bug】上传时出现黄色区域，无法上传

### ISSUE THREAD

**Issue by quanzaiyu** [qiniu/kodo-browser#33]
上传时，按如下步骤复现Bug：

1. 列表向下滑动
2. 拖动需要上传的文件进入Kodo
3. 在Kodo中移动
4. 将需要上传的文件移出Kodo，放弃上传

效果请到如下地址查看：

[https://kan.xiaoyulive.top/bug/GIF.gif](https://kan.xiaoyulive.top/bug/GIF.gif)

经此操作，黄色区域会一直停留显示到Kodo之中，无法去除，黄色区域无法响应正常操作，只能响应文件拖拽上传。

再次拖动其他需要上传的文件到非黄色区域，无响应，不能上传。

**Comment by bachue** [comment]
@quanzaiyu 重现了，将会在之后的版本修复。

**Comment by Jessie-shsh** [comment]
1.0.11版本已修复此问题
