### ISSUE TITLE
建议增加切换账号的时候可以直接新增账号，而不用退出登录再添加。

### ISSUE THREAD

**Issue by nnqc** [qiniu/kodo-browser#35]
客户端软件很好用，有一点不方便，就是切换账号的时候比如我想新增其他账号要先退出，建议增加个新增账号的按钮跳转。
另外我选择公有云登录，但我私有云文件也可以看到，这个跟登录的时候选择私有云有什么区别呢？

移动文件的时候可否加个选择窗口，直接移动到所选文件夹，而不用我自己找到文件夹再粘贴一次。

**Comment by Jessie-shsh** [comment]
切换账号的时候比如我想新增其他账号要先退出，建议增加个新增账号的按钮跳转。
答：客户端已经实现了「记住密钥」和「切换账号」的功能。登录成功过、并被勾选记录的账号，可以在切换账号时直接选择、自动切换登录。

移动文件的时候可否加个选择窗口，直接移动到所选文件夹，而不用我自己找到文件夹再粘贴一次。
答：目前操作方式与常规的文件操作方式一致，且在目标路径下粘贴能更方便、直观地确认操作结果。

**Comment by Jessie-shsh** [comment]
我选择公有云登录，但我私有云文件也可以看到，这个跟登录的时候选择私有云有什么区别呢？

这里描述的是，公有云登录时，私有空间也能看到吗？私有云登录的意思是，使用客户端工具对接管理私有云存储系统的资源，不是指公开空间、私有空间
