### ISSUE TITLE
建议对大量文件下载进行优化

### ISSUE THREAD

**Issue by Skqing** [qiniu/kodo-browser#4]
20000多条数据加载的时候卡的很，并且下载超级慢，希望能优化

**Comment by Skqing** [comment]
实际上2000多开始就比较慢了

**Comment by Jessie-shsh** [comment]
关于文件列表加载卡顿，已经在做优化迭代，支持分页加载模式。
后续还会继续对文件下载做处理优化，内部跟踪issue编号 KODO-10301 。

**Comment by bachue** [comment]
@Skqing 请尝试下新的版本 v1.0.13，已经优化了下载质量

**Comment by lingyun820** [comment]
下载几万条文件和几个目录，文件没有下载全
