### ISSUE TITLE
建议新增一个上传文件夹的功能

### ISSUE THREAD

**Issue by 353869750** [qiniu/kodo-browser#42]
想文件下所有的文件，并且是和他的结构一致的。要按照本地目录结构一个一个创建目录结构，还有一个文件一个文件的上传，很老火的。

**Comment by Jessie-shsh** [comment]
你好～工具支持上传文件夹，windows系统下请直接拖拽文件夹到上传界面

**Comment by 353869750** [comment]
哦，我试试，谢谢
