### ISSUE TITLE
建议支持在线文件搜索

### ISSUE THREAD

**Issue by JunfeiHu** [qiniu/kodo-browser#43]
不支持在线文件搜索，目前只支持分页加载完成的部分进行搜索。

**Comment by Jessie-shsh** [comment]
你好，客户端搜索是直接请求服务端查询得到结果的。请确认下是否输入了正确的文件名，实际检索文件名=当前目录+输入的检索文件名
![image](https://user-images.githubusercontent.com/14085670/105985400-5deccd00-60d6-11eb-8b60-67cf7be66f22.png)
