### ISSUE TITLE
1.0.13修改文件上传报错

### ISSUE THREAD

**Issue by echoiron** [qiniu/kodo-browser#46]
使用1.0.13操作脚本(文本)文件后，点击完成报下方错误

```bash
ERR_INVALID_ARG_TYPE: The "path" argument must be of type string. Received type object
```

![image](https://user-images.githubusercontent.com/52339367/111857622-bcfbef00-896d-11eb-9281-3a5be0a776f8.png)

**Comment by bachue** [comment]
@echoiron 好的，我这里看下

**Comment by Jessie-shsh** [comment]
@echoiron 你好，我们这边使用 ps1 文件修改后保存，没能复现出上述报错。你这边是否可以提供更多的信息，比如在什么平台使用的？是任意修改都不能保存吗？方便的话，是否可以提供修改前后的内容给我们

**Comment by zlmica** [comment]
Mac系统 V1.0.13，任意文件修改任意信息，报同样的错误

> @echoiron 你好，我们这边使用 ps1 文件修改后保存，没能复现出上述报错。你这边是否可以提供更多的信息，比如在什么平台使用的？是任意修改都不能保存吗？方便的话，是否可以提供修改前后的内容给我们

**Comment by bachue** [comment]
@zlmica @echoiron 我们已经重现了这个问题 将在 v1.0.13.1 解决这个 bug

**Comment by bachue** [comment]
@zlmica  @echoiron  我们的新版本可以解决这个问题了 https://github.com/qiniu/kodo-browser/releases/tag/v1.0.13.1
