### ISSUE TITLE
1.0.13获取外链不支持自定义域名

### ISSUE THREAD

**Issue by ionull** [qiniu/kodo-browser#47]
如题。

**Comment by bachue** [comment]
@ionull  应该是支持的？除非是私有云模式。

**Comment by ionull** [comment]
@bachue 上个版本都没这个问题的，确认是新版本才出问题。

**Comment by bachue** [comment]
@ionull 能否给个截图看看？

**Comment by ionull** [comment]
![Uploading Screen Shot 2021-03-24 at 8.48.03 PM.png…]()

**Comment by ionull** [comment]
<img width="567" alt="Screen Shot 2021-03-24 at 8 48 03 PM" src="https://user-images.githubusercontent.com/242295/112313071-6cc0bc00-8ce2-11eb-8ca9-726fade9b9e5.png">

**Comment by ionull** [comment]
这里以前是可以选择自己域名的

**Comment by bachue** [comment]
@ionull 这个存储空间是华东区的吗？

**Comment by ionull** [comment]
@bachue 你好，是的

**Comment by bachue** [comment]
@ionull 我们的新版本可以解决这个问题了 https://github.com/qiniu/kodo-browser/releases/tag/v1.0.13.1

**Comment by ionull** [comment]
可以了，多谢。
