### ISSUE TITLE
新版生成的链接，符号进行了Unicode编码

### ISSUE THREAD

**Issue by echoiron** [qiniu/kodo-browser#49]
中文字符进行Unicode编码比较合理
asc常见的符号，如正斜杠(/)就没必要做转换
虽然不属于bug问题，但还是希望能改进，复制的链接会清爽一些
![image](https://user-images.githubusercontent.com/52339367/113409380-bf396100-93e3-11eb-8eef-77eb79896644.png)

**Comment by bachue** [comment]
会在下个版本里改进的。

**Comment by bachue** [comment]
在新的版本 v1.0.13.2 已经改进
