### ISSUE TITLE
目录中文件超过1000条没有分页功能

### ISSUE THREAD

**Issue by TomWangKing** [qiniu/kodo-browser#51]

**Comment by TomWangKing** [comment]
下载了最新版本，原来是1.0.11，新版的有分页，但是超过1500条文件后， 显示 正在加载更多

**Comment by Jessie-shsh** [comment]
同样的空间，旧版客户端，都是能正常列举完的吗？工具使用的系统平台是？我们这边 3000+ 条文件，是能正常列举的。是七牛公有云客户，麻烦工单提交下账号和空间信息？
