### ISSUE TITLE
点击生成链接出现转义

### ISSUE THREAD

**Issue by TomWangKing** [qiniu/kodo-browser#52]
https://static.xxxxx.com/Public%2Fapk%2Fanzhuangbao1.4.0.apk

**Comment by TomWangKing** [comment]
v1.0.13.1

**Comment by bachue** [comment]
@TomWangKing 已知问题（也不算 bug），会在下个版本里改进的。

**Comment by bachue** [comment]
在新的版本 v1.0.13.2 已经改进
