### ISSUE TITLE
进入bucket之后加载时间太长

### ISSUE THREAD

**Issue by zhongqc** [qiniu/kodo-browser#54]
当bucket中已经有比较多文件时，使用kodo进入bucket之后的加载时间很长，在bucket中创建目录之后也一样需要等待很长的加载时间

**Comment by bachue** [comment]
可以启用分步加载模式

<img width="974" alt="Screen Shot 2021-04-25 at 6 58 47 PM" src="https://user-images.githubusercontent.com/321962/115990883-49966e80-a5f8-11eb-8d2b-15d0466c7f8b.png">

并设置更小的加载条目数

<img width="998" alt="Screen Shot 2021-04-25 at 6 59 49 PM" src="https://user-images.githubusercontent.com/321962/115990915-764a8600-a5f8-11eb-9f5b-b689c28d3435.png">

**Comment by zhongqc** [comment]
使用该设置项之后仍然很慢，并且根据实验感觉设置该参数后加载的是文件夹数，会递归查询到下边所有的文件

**Comment by bachue** [comment]
@zhongqc 建议和技术支持联系下 https://support.qiniu.com/tickets/new/form?category=%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8&space=%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8 主要是申报下账户和加载时间很长的 bucket 名称，我们这边尝试复现下。

**Comment by zhongqc** [comment]
好的
