### ISSUE TITLE
能优化一下上传体验吗?

### ISSUE THREAD

**Issue by a364176773** [qiniu/kodo-browser#55]
1个文件基本上就卡着不动,看起来速度3MB其实就几百kb,过半天进度条和上传大小/总大小才有变化,同时多传几个文件卡成狗

**Comment by bachue** [comment]
@a364176773 用的是最新的 v1.0.13.x 吗？

**Comment by a364176773** [comment]
> @a364176773 用的是最新的 v1.0.13.x 吗？

是的,上传文件大小大概是1.8g左右

**Comment by bachue** [comment]
@a364176773 电脑配置和操作系统分别说下？

**Comment by bachue** [comment]
@a364176773 另外，请确认断点续传是打开的。

**Comment by a364176773** [comment]
> @a364176773 电脑配置和操作系统分别说下？

i5-8300 24g内存 1.5t ssd win10

**Comment by a364176773** [comment]
> @a364176773 另外，请确认断点续传是打开的。

确定打开

**Comment by liuwenkai1023** [comment]
和OSS Brower相比，用户体验几乎为零，16000张图片，共200M，上传24小时都上传不完，基本上5-10s才能上传一张......希望优化一下

**Comment by a364176773** [comment]
> 和OSS Brower相比，用户体验几乎为零，16000张图片，共200M，上传24小时都上传不完，基本上5-10s才能上传一张......希望优化一下

+111111111111....

**Comment by seven-cm** [comment]
我太难了，上传18M的文件夹，就这么慢；就不能优化一下？

**Comment by lihsai0** [comment]
@a364176773 @liuwenkai1023 @seven-cm 

[v1.0.18](https://github.com/qiniu/kodo-browser/releases/tag/v1.0.18) 优化了上传时遍历本地目录速度、本地任务调度速度。

对大量小文件场景应该有一定帮助。

麻烦各位试用反馈。

测试场景：1000 个 64KB 文件上传。


https://user-images.githubusercontent.com/17806506/177984707-729ebdae-5573-4ce1-9894-e2f7e4d84fc0.mp4

**Comment by rielzhou** [comment]
怎么不能上传文件夹呢？

**Comment by lihsai0** [comment]
> 怎么不能上传文件夹呢？

@rielzhou windows平台吗？windows 平台只能拖入文件夹，选择窗体无法选择文件夹。

如果还有疑问，请注明运行环境信息与版本号，最好可以有动图或视频。
