### ISSUE TITLE
文件特别多的时候特别卡

### ISSUE THREAD

**Issue by wlight** [qiniu/kodo-browser#6]
在 Bucket  里文件特别多的时候（10000+文件），在进入 Bucket 的时候会一下把所有的文件都列出来，这样就会特别卡，所以能不能优化一下，不要一下把所有的文件都列出来啊

**Comment by bachue** [comment]
@wlight  之后的版本会实现分页加载的功能

**Comment by Jessie-shsh** [comment]
内部跟踪issue编号 KODO-10217

**Comment by bachue** [comment]
@wlight 刚刚发布的 v1.0.10 版本已经支持文件列表的分步加载，谢谢
