### ISSUE TITLE
[Feature]能不能加一个修改存储类型的功能？最好是批量修改

### ISSUE THREAD

**Issue by mdzz0** [qiniu/kodo-browser#62]
kodo-browser里面不支持修改存储类型，上传的时候也不能指定存储类型；

现在文件上传之后还得去web控制台修改存储类型，而且web版本的控制台里面还只能单个修改，

另外：生成外链的时候，web控制台已经设置了一个默认域名，kodo-browser里面还需要再选择（这个倒是小问题）

**Comment by Jessie-shsh** [comment]
修改存储类型的功能，客户端正在开发中

**Comment by mdzz0** [comment]
好的，感谢

**Comment by bachue** [comment]
@mdzz0  Kodo Browser v1.0.14 发布了
