### ISSUE TITLE
建议增加直连链接

### ISSUE THREAD

**Issue by daqueque** [qiniu/kodo-browser#9]
每次都要单独输入外部链接。

**Comment by Jessie-shsh** [comment]
请更详细、清晰地描述一下您的问题或需求。

**Comment by daqueque** [comment]
> 请更详细、清晰地描述一下您的问题或需求。

公开空间绑定的域名 abc.com
公开空间储存文件名 123.jpg
-----------
储存的文件点击点击获取永久外联地址：https://abc.com/123.jpg

**Comment by daqueque** [comment]
> 请更详细、清晰地描述一下您的问题或需求。

可以考虑一下吗？大佬

**Comment by Jessie-shsh** [comment]
考虑评估中，结果后续会在此同步

**Comment by daqueque** [comment]
> 考虑评估中，结果后续会在此同步

感谢，因为每次这样操作都要手动去编辑链接，太麻烦了。

**Comment by yancheng199287** [comment]
外链分享  时间，建议可以设置默认无限时间，链接地址建议用自定义域名+文件地址

**Comment by imyellow** [comment]
另外一个图形客户端有此功能，可供参考，并且有公开和非公开 bucket 设置
https://github.com/willnewii/qiniuClient

各有所长

**Comment by cycychenyi** [comment]
> 外链分享 时间，建议可以设置默认无限时间，链接地址建议用自定义域名 + 文件地址

附议！

**Comment by Jessie-shsh** [comment]
已纳入迭代规划中，内部跟踪issue编号 KODO-10300

**Comment by Jessie-shsh** [comment]
1.0.11版本，可以支持使用cdn域名生成外链，公开空间可以生成永久连接。
